import type { LayoutSetting } from "~@/stores/app";

export default {
  title: "Lxx",
  theme: "light",
  isShowChangeTheme: false,
  logo: "/logo.svg",
  // logo: 'https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg',
  collapsed: false,
  drawerVisible: false,
  colorPrimary: "#1677FF",
  layout: "mix",
  contentWidth: "Fluid",
  fixedHeader: false,
  fixedSider: true,
  splitMenus: false,
  header: true,
  menu: true,
  menuHeader: true,
  footer: false,
  colorWeak: false,
  multiTab: false,
  multiTabFixed: false,
  headerHeight: 48,
  copyright: "这是一个copyright文字",
  waterMarkWord: "lxx",
  isShowUserAvatar: true,
  isShowSettingDrawerIcon: true,
  isShowWaterMark: false,
  accordionMode: true,
} as LayoutSetting;
